### ISSUE TITLE
High CPU usage?

### ISSUE THREAD

**Issue by SanderVocke** [SanderVocke/shoopdaloop#125]
Large amount of loops = ok, but the base amount of cpu usage seems high.

Didn't measure this in any respectable way - just noticed that the laptop fan immediately starts blowing when shoopdaloop starts, and that this doesn't happen for other real-time idle programs.

**Comment by zigmhount** [comment]
I can confirm, shoopdaloop uses 30% of my CPU even when everything is stopped (Sync loop stopped, 5 tracks are all stopped). ~ 10% at launch, with no tracks and Sync loop stopped.

**Comment by SanderVocke** [comment]
Thanks for confirming. May I ask what latency you're running at?

FYI, I think that this CPU usage is not on the audio thread, but instead related to the way the UI is refreshing its state of what the back-end is doing. So it shouldn't affect your audio performance much. But it is still annoying and definitely something to work on (especially since it scales so badly with the amount of tracks/loops).

**Comment by SanderVocke** [comment]
Interestingly, just ran a Windows session with several tracks and CPU usage stayed at <3%. Who knows, maybe this is a Windows-only issue.

**Comment by SanderVocke** [comment]
@zigmhount: did you have any plugins running? Note that any track which has its input unmuted (the "ear symbol") will have its FX active and running. Some are prone to use a lot of CPU. Muting all inputs would give a "clean" measurement.

**Comment by SanderVocke** [comment]
Well, this was silly. It turned out to be too eager polling on the MIDI control ports. Added a reasonable interval there (50ms). Closing, although it is still on a branch - will merge to master soon.

**Comment by zigmhount** [comment]
Sorry for not giving feedback here, but glad to see that you managed to fix this 👍🏼 

FWIW I think I was testing with only MIDI inputs, does the ear symbol also affect MIDI input?

**Comment by SanderVocke** [comment]
Hi @zigmhount, no worries! This was pretty hard to find. The culprit was polling on the MIDI control ports as fast as possible (not the instrument MIDI inputs).

I will upload a new build tonight with this fix.

Yes, the ear symbol affects the instrument MIDI input of the track. But not any MIDI control input ports.

**Comment by SanderVocke** [comment]
New build is uploaded.
